Fix warnings when building with GCC
Gnarus-G/maccel pull request #38
Opened 2024-12-08 15:07 UTC by gnusenpai

Fixing the warnings is necessary for a successful build when the kernel is built with the CONFIG_WERROR option. This option is default in at least the upstream kernel config.

This PR is marked as a draft because:

1. It needs testing with clang.
2. I'm not sure how the nested `#ifdef` in `driver/dbg.h` should be formatted.
3. Removing the `static` keyword from the fixedpt functions creates warnings in the rust CLI build. While it technically still works, I'm not sure how to fix these. Maybe a different approach should be taken.
Changing `extern` to `static` in the sensitivity function is an alternative fix, but it causes the CLI build to fail until changed back. Building the module with `static`, reverting it to `extern`, and then building the CLI works, if that's useful information.

2024-12-08 18:42 UTC, MCPO-Spartan-117 commented
> 1. It needs testing with clang.

No errors on clang.

> 2. I'm not sure how the nested `#ifdef` in `driver/dbg.h` should be formatted.

Should be more modularized but the `\`s in the functions make that complicated so i don't know how to go about that.

> 3. Removing the `static` keyword from the fixedpt functions creates warnings in the rust CLI build. While it technically still works, I'm not sure how to fix these. Maybe a different approach should be taken.
Changing `extern` to `static` in the sensitivity function is an alternative fix, but it causes the CLI build to fail until changed back. Building the module with `static`, reverting it to `extern`, and then building the CLI works, if that's useful information.

@Gnarus-G
Are there any functions that actually need to be static? like need their own version of these functions/results?

2024-12-08 19:03 UTC, Gnarus-G commented
If you mean just the functions in the fixedpt header file, then no I can't think of a reason they "need" to be.

2024-12-09 06:16 UTC, gnusenpai commented
I figured out a different way to address point number 3 by making a separate wrapper function for the rust side; see the new commit: c045d82. This way fixes the warnings on both the C and rust sides.

> Should be more modularized but the `\`s in the functions make that complicated so i don't know how to go about that.

@MCPO-Spartan-117
I tried, but yeah, putting an `#ifdef` within a `#define` is either just not possible or really messy. The rest of the file does similar duplication, so it's not really out of place.

2024-12-09 17:16 UTC, MCPO-Spartan-117 requested changes

2024-12-09 17:16 UTC, MCPO-Spartan-117 commented on driver/dbg.h
> +#ifdef __clang__
```suggestion
#if defined __KERNEL__ && defined __clang__
```

2024-12-09 17:16 UTC, MCPO-Spartan-117 commented on driver/dbg.h
>  #ifndef __KERNEL__
```suggestion
#elif defined __KERNEL__
#define dbg_k(fmt, ...)                                                        \
  do {                                                                         \
    if (DEBUG_TEST)                                                            \
      printk(KERN_INFO "%s:%d:%s(): " #fmt "\n", __FILE__, __LINE__, __func__, \
             __VA_ARGS__);                                                     \
  }                                                                            \
  while (0)
#else
```

2024-12-12 13:19 UTC, gnusenpai commented
I'm just gonna open this up, the code styling is up to @Gnarus-G.

2024-12-14 20:01 UTC, MCPO-Spartan-117 commented on driver/accel_rs.h
Don't know about this but i don't have any `C to Rust` bridge knowledge so i don't know if this is considered a hack.

2025-01-27 00:37 UTC, merged